ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autofix_commit_msg: 'fix(pre_commit): 🎨 auto format pre-commit hooks'
  autoupdate_commit_msg: 'chore(pre_commit): ⬆ pre_commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        (\.idea/.*)|
        (.+/\.idea/.*)|
        patches/.*
      )$
  - id: trailing-whitespace
    exclude: ^patches/
  - id: check-executables-have-shebangs
  - id: check-toml
  - id: check-case-conflict
  - id: check-added-large-files
    args: [--maxkb=4096]
    exclude: ^logo/
  - id: detect-private-key
  - id: forbid-new-submodules
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --indent=4]
  - id: mixed-line-ending
